language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
env:
  - RUNNER=node
  - RUNNER=karma
matrix:
  # no need to run karma against old nodejs versions
  exclude:
    - nodejs: "0.8"
      env: RUNNER=karma
    - nodejs: "0.6"
      env: RUNNER=karma
notifications:
  email:
    on_success: change
    on_failure: change
script: "./tools/bin/travis-tests"
